common/core/bin/start, common/horizon/bin/start, common/postgresql/.pgpass, common/supervisor/etc/supervisord.conf, pubnet/core/etc/stellar-core.cfg, start, testnet/core/etc/stellar-core.cfg
This PR started out as a simple addition to the image but quickly became a collection of general improvements described below:
- An optional cache for history can now be supplied to speed up container recreation and save on bandwidth.  To utilize, map a populated history archive onto the path `/opt/stellar/history-archive`
- Lowered the amount of historical ledger data fetched to approximately 1 day, down from approximately 1 week.  This change is intended to further increase catch up's speed.
- Added a `.pgpass` file into the home directories of root and stellar, allowing for more easy access to the postgres
- Add support for overriding `STELLAR_MODE`
=> Many improvements

Dockerfile
Apparently having a high UID causes the lastlog file to become very large. 
Some more info: https://bugzilla.redhat.com/show_bug.cgi?id=771286
```
$ docker images
REPOSITORY                                    TAG                 IMAGE ID            CREATED             SIZE
stellar/quickstart                            latest              c704f9ede93d        5 minutes ago       676MB
```
I switched to using `useradd` instead of `adduser` because I don't think `adduser` supports the `--no-log-init` switch.
Fixes #13
=> Fix high UID causing large image size

Dockerfile, README.md, standalone/core/etc/stellar-core.cfg, start
By using the `--standalone` flag a private network will be created instead of joining the pub- or testnet.
=> Add standalone option

start
The start script contained extra tabs/whitespace which caused NETWORK=standalone to never be set. Instead passing --standalone to the end of a docker run command threw an unknown container arg error.
This simple formatting fix worked for me and I was able to successfully build using make and fire up a standalone container. 
Hope this helps.
=> --standalone was not working

.travis.yml, common/supervisor/etc/supervisord.conf, start, travis.go
Update image to use debian stretch, including Postgres 9.6 (instead of 9.4 in the previous version), because `stellar/base` image was updated.
Not sure why but `kill $CURRENT_POSTGRES_PID` command is not working now. I thought that maybe it's an issue with my docker installation however I experienced the same issue on travis. Changed this command to equivalent: `killall postgres`.
Added tests that start testnet/pubnet containers and wait until Horizon starts ingesting ledgers.
=> Debian stretch updates

start
When restarting a standalone core the status remains "Joining SCP", this fix solves that.
=> Set forcescp when restarted in standalone mode

start
Turns out that in some cases you just want nothing to happen when it comes to upgrades (some people put upgrades in their config file)
So now, if you pass in `none` for the protocol version, it will do nothing.
This should close out #56 completely at this point.
=> allow to disable protocol upgrade in standalone mode

start
When running in disconnected mode the init-core-scp command would fail. This change moves the pushd and chown commands up to ensure the image works as expected when running in standalone mode.
this fixes https://github.com/stellar/docker-stellar-core-horizon/issues/122
=> Ensured 'chown-core' is executed before 'init-core-scp' in standalone mode

pubnet/core/etc/stellar-core.cfg, testnet/core/etc/stellar-core.cfg
`stellar/quickstart` image is meant to be a fast way to sync with Stellar network for development/test purposes. Downloading 8640 ledgers (12 hours) slows down the startup time. This should also fix tests that currently timeout.
=> Decrease CATCHUP_RECENT in Stellar-Core config

.travis.yml
Tests were disabled in https://github.com/stellar/docker-stellar-core-horizon/commit/217f3a24f5847dac69fab7c23a9a423c32247c96#diff-354f30a63fb0907d4ad57269548329e3R8 because they were timing out but it was fixed in https://github.com/stellar/docker-stellar-core-horizon/commit/95ca5fe598b11fe77cfb8384977be804805a7428.
=> Enable TAG_TESTING=1 NETWORK=pubnet tests

start
Horizon 1.0.0 requires history archives to build internal ledger state. This breaks standalone mode because Stellar-Core stores history data in local file system. To solve this we start local web server that serves files from history archive.
This is a quick fix: when history is initialized using `stellar-core newhist` command the `currentLedger` value is equal `0` and makes Horizon wait for a valid, non-zero value. Because of this Horizon is able to start ingesting after 64 ledgers (when first checkpoint is created).
To fix this permanently Stellar-Core or Horizon code needs to be changed.
Close #160.
=> Fix standalone horizon 1.0.0

.circleci/config.yml
This commit adds a Circle CI job which is invoked whenever a commit is pushed to master.
The job will build and publish the `stellar/quickstart:latest` and `stellar/quickstart:testing` docker images.
We will need to include dockerhub credentials in the `DOCKER_USER` and `DOCKER_PASS` environment variables so that circle ci will have the permissions to push to the `stellar/quickstart` image repo.
=> Add CI job to publish docker image on merge to master

start
This commit runs `horizon expingest init-genesis-state` to allow faster ingestion in standalone mode (see for the previous solution that waits for the first checkpoint before starting ingestion: https://github.com/stellar/docker-stellar-core-horizon/pull/164). Requires: https://github.com/stellar/go/pull/2910.
=> Run init-genesis-state in standalone

Dockerfile, Dockerfile.testing, README.md, common/core/bin/start, common/horizon/bin/horizon, common/supervisor/etc/supervisord.conf, dependencies, install, start
This change removes dependency on the stellar-base image.
I tested testnet and pubnet modes and they work fine. Standalone mode is broken but it's also broken in the master branch
=> Switch to ubuntu 16.04 base and use apt packages

pubnet/core/etc/stellar-core.cfg, testnet/core/etc/stellar-core.cfg
their presence is confusing as there is nothing that populates them, and this only triggers error messages when catching up
=> remove local cache archive from core config files

README.md
Add some more details about the different network options the container supports, and how to use the standalone network, and what the root account is.
@accordeiro and I both found using the standalone network not particularly intuitive. It isn't clear what the root account is because it is buried in logs that are not easy to get to. The only discussion about the network options is buried in a text block, and we could reiterate those options in sections to make it clearer to the reader. It also seems useful to include the root account and its seed since they are fixed.
=> Add some more details about the different network options

start
**WHAT**
make start script formatting consistent by using tabs instead of spaces
**WHY**
after reviewing my PR of this repo @leighmcculloch pointed out there's inconsistent spacing. So fixing that by replacing 2 spaces with a tab, which seems to be the predominant formatting in the file.
note: it looks like google recommends using spaces: https://google.github.io/styleguide/shellguide.html#formatting
but since tabs was already the predominant formatting here I went with that instead.
=> use tabs not spaces in start script

.do/deploy.template.yaml, README.md
DigitalOcean should be pointing at master branch and not the feature branch (had to leave as feature branch in previous [PR](https://github.com/stellar/docker-stellar-core-horizon/pull/276) until it was merged for testing because needs the .do/deploy.template.yaml file to work)
=> point DigitalOcean to master branch

dependencies, install
Install `rsync` in `dependencies` instead of `install`.
`rsync` is a general dependency of the image, because it is used by the `start` script. It is not a dependency specifically for installing `stellar-core` or `stellar-horizon`, like `gnupg1` and `wget` are. It should be installed with the other dependencies.
This wouldn't appear to matter much, but for folks hacking on the docker image who might comment out the `install` script it is very inconvenient that doing so breaks other parts of the image that have nothing to do with the install script.
=> Install rsync in 'dependencies' instead of 'install'

test.go
Increase the timeout on the test that runs in CI to 2 hours.
The test is frequently timing out on CI runs for pubnet. According to logs I'm looking at across multiple PRs that have failed consistently it seems like it's just taking a long time to catch up ingesting.
The scale of the data in pubnet and it's difficulty for us to even run a simple test in the quickstart image with it could be a more motivation for us to stop supporting pubnet in this quickstart image (#305). Regardless of whether we do that though, upping this timeout should give us confirmation if it truly just needs more time.
=> Increase timeout for test to 2 hours

.github/workflows/test.yml, Dockerfile.dev, Makefile
Add a `Dockerfile.dev` dockerfile that builds `stellar-core` and `stellar-horizon` from source and uses those source builds in the quickstart image built.
Add a ci workflow that exercises the new `Dockerfile.dev`:
While working on the CAP-21 and CAP-40 fork of stellar-core and stellar-horizon I found it helpful to be able to build a quickstart image that had updates without having to rebuild debs, because the deb build process is extremely slow and complete, and involves fiddling with a very complicated and confusing Jenkins setup.
Both stellar-core and stellar-horizon have dockerfiles in their repos that build from source. Stellar-core has `Dockerfile.testing` and Stellar-Horizon has `Dockerfile.dev`. We can leverage those dockerfiles to build a quickstart from source.
=> Add Dockerfile.dev that builds stellar-core and horizon from source

.github/workflows/Dockerfile.dev.yml
Run the Dockerfile.dev builds on a schedule.
They're the most likely to break since they import stellar-core and horizon from source builds. It's not really clear how well they will stay green, but we can adjust it easily if it turns out it breaks a lot.
The other dockerfiles don't need a schedule because they install from prebuilt debs they should be reliable and stable.
I chose the schedule time so it runs over night before each work day.
=> Run the Dockerfile.dev build on a schedule

.github/workflows/Dockerfile.dev.yml, .github/workflows/Dockerfile.testing.yml, .github/workflows/Dockerfile.yml
Cancel builds for non-protected (non-master) branches and pull requests when a new build is pushed to the branch.
The builds in this repo take a long time and when iterating on a PR it would be ideal if only the latest commit runs a build.
For protected branches, like the master branch, we should probably still have the build run on every commit so we know if it is or was broken at any point.
=> Cancel superseded builds for non-protected branches

.github/workflows/Dockerfile.dev.yml
Remove the custom options used in building stellar-core.
They speed up compilation by about 7 mins, but slow down the tests by almost 1 hour. Clearly they weren't worth it!
=> Remove options from stellar-core when building for the dev image

.github/workflows/stale.yml
Add workflow dispatch trigger to stale workflow.
To allow us to manually trigger it. So I can trigger it and test it.
=> Add workflow dispatch trigger to stale workflow

.github/actions/push/action.yml
Fix the image URL that is posted to GitHub commit statuses so it is correctly set for Docker Hub.
=> Fix image url in statuses

.github/workflows/Dockerfile.testing.yml
Include the git revision on the testing image in the same way it is included on the latest and dev images.
It makes it trivial to look at an image and know which commit of the repo the image was built from. It is something we have on the latest image and the dev image, and I missed it on the testing image.
=> Include revision label on testing image

.github/workflows/Dockerfile.dev.yml, Makefile
Use https:// instead of git:// for git docker builds.
The main trigger for this change is that GitHub stopped supporting `git://` yesterday because it is insecure. I should never have used `git://` because it is insecure, so this is a good change regardless.
This change has no functional impact on the build.
Note the `.git` is required on the tail of the URL as Docker/Podman use it on the URL to identify that this is a git repo and not a tar download.
=> Fix failing master build

.github/workflows/Dockerfile.dev.yml, Dockerfile.dev, Makefile
Build only Horizon's `builder` stage when building the dependencies for Dockerfile.dev.
Horizon's dockerfile builds more than Horizon, it also installs and sets up stellar-core, because that is a dependency of Horizon if you choose to run Horizon that way. The Dockerfile.dev image uses the Horizon dockerfile to build Horizon, and doesn't actually need any other applications that the Horizon dockerfile installs. Docker makes it trivial with multi-stage builds to build only specific stages, which is useful when one needs to run the stages that build an application but don't need the stages for running the application. This strategy is useful here since we only need to build Horizon, not run it from the image.
The same pattern could be employed for the other services, stellar-core and …
=> Make Dockerfile.dev build natively on arm64

Makefile
Update `Makefile` to always build the main and testing builds with the `linux/amd64` platform.
For developers on other architectures these make commands fail because stellar-core is only available for install via deb for amd64.
Apple Silicon computers are becoming more prevalent and are arm64.
=> Update makefile to always build on amd64 platform

Makefile, start
Use 0.5 native base reserve in standalone.
Standalone mode uses the original base reserve the network had back at the first protocol, which was 10 native. Pubnet and testnet use 0.5 native because at some point the base reserve was reduced. Having standalone have a higher one is inconvenient for testing and doesn't really add any value.
Close #343
=> Use 0.5native base reserve in standalone

.github/workflows/Dockerfile.dev.yml, .github/workflows/Dockerfile.testing.yml, .github/workflows/Dockerfile.yml
Add complete CI job that we can make a required check instead of requiring individual jobs.
This is the pattern we use on newer repositories and this brings this repository up-to-date.
Having a single CI job that is a required check moves the definition of what is required down to the repo and out of the GitHub settings. This has a couple advantages:
- It is easier to express dependencies inside the GitHub Actions YAML files. We can say that all builds are required, or all tests, and it is a single word that will require all instances of a matrix. It is harder to express the same in GitHub required check configurations because each individual matrix instance has to be listed separately.
- Developers can control what builds are required by editing repo code, rather than getting an …
=> Add complete CI job that we can make a required check

.github/workflows/Dockerfile.dev.yml, .github/workflows/Dockerfile.testing.yml, .github/workflows/Dockerfile.yml, Dockerfile, Dockerfile.dev, Dockerfile.testing, Makefile, README.md, common/nginx/etc/nginx.conf, common/soroban-rpc/bin/start, common/soroban-rpc/etc/soroban-rpc.env, common/supervisor/etc/supervisord.conf.d/soroban-rpc.conf, standalone/nginx/etc/nginx.conf, standalone/supervisor/etc/supervisord.conf.d/friendbot.conf, start, test_soroban_rpc_up.go
Initial rough changes made on the image to confirm a spike that soroban-rpc will work in the image container runtime without conflict at same time that horizon is running with captive core and be able to use Horizon's API endpoints.
soroban-rpc is not launching it's own captive-core or doing any ingesting, instead it is just connecting to the horizon API HTTP service per latest changes related to getAccount on [#4556](https://github.com/stellar/go/issues/4556) by @tamirms.
I've done live testing on this branch to confirm behavior:
```
$ make build-dev GO_REPO_BRANCH=pull/4591/head
$ docker run --platform linux/amd64 --rm -it -p "8000:8000" --name stellar stellar/quickstart:dev --standalone --enable-soroban-rpc --enable-horizon-captive-core
``` 
after startup, have to wait for first 63 …
=> Adding soroban-rpc service to quickstart for standalone network

common/friendbot/bin/start, common/soroban-rpc/bin/start
check horizon ingestion ledger count from supervisor startup to determine when horizon service is truly available, friendbot and soroban-rpc use the same mechanism of to wait on horizon their respective log files in `/var/log/supervisor/` will show their looping attempts to check horizon state. this is more pronounced wait time when `--enable-horizon-captive-core` is used. 
i tested with:
```
$ make build-dev
$ docker run --platform linux/amd64 --rm -it -p 8000:8000 --name stellar stellar/quickstart:dev --standalone --enable-horizon-captive-core --enable-soroban-rpc
=> wait loop for horizon based on ingest ledger number

Dockerfile.soroban-dev, common/nginx/etc/nginx.conf
Noticed that from the nginx localhost:8000 on quickstart, when accessing horizon, the horizon HAL links were being written with the local back-end host:port info instead of nginx proxy host:port:
```
"_links": {
"account": {
"href": "http://127.0.0.1:8001/accounts/{account_id}",
"templated": true
},
....
```
this changes proxy to forward proxyhost:proxyport to backing services instead.
Also, created a tag to refer to soroban rpc source version to be used during docker build - [soroban-rpc-v0.0.1-alpha](https://github.com/stellar/go/releases/tag/soroban-rpc-v0.0.1-alpha)
=> nginx, fix host/port forwarding

.do/deploy.template.yaml
removing random passphrase flag from digitalocean button start command
causing an error with friendbot when the container starts, see more [on slack](https://stellarfoundation.slack.com/archives/C030Z9EHVQE/p1668543220518399?thread_ts=1666107837.290549&cid=C030Z9EHVQE)
=> remove random passphrase flag from digitalocean button

Makefile, README.md
Update the quickstart image building to use the updated soroban-rpc from the soroban-tools repository.
The current makefile takes the soroban rpc and the horizon from their master/main branches. That is wrong and need to be addressed ( in a future PR )
=> quickstart: update soroban-rpc repository

.github/workflows/Dockerfile.dev.yml, Dockerfile.dev, Makefile
Correct the path of where to find the soroban-rpc binary in the soroban-rpc image used for building. When building the soroban-rpc only build the `build` target.
The binary is in a different location in this image and it looks like we're using the wrong location.
The `--target build` is required to only build the soroban-rpc itself, and not build the rest of the image which has a dependency on stellar-core.
=> Fix soroban-rpc in Dockerfile.dev

.github/workflows/build.yml, .github/workflows/manifest.yml
Remove the prefix "false" from the names of images when released from master.
I changed how the image name was generated in #397 and accidentally introduced the word "false" into the prefix when the image is built not from a pull request. This change reverts the change to the image name.
=> Fix name of images when released from master

common/nginx/etc/nginx.conf
Pass through host from http request to horizon and soroban-rpc.
This results in whatever is in the HTTP request Host header to be echoed back in responses in the `_links` field.
For example:
Request:
```http
GET / HTTP/1.1
Accept-Encoding: gzip
Host: example.com
User-Agent: httpie-go/0.7.0
```
Response:
```http
HTTP/1.1 200 OK
Cache-Control: no-cache, no-store, max-age=0
Connection: keep-alive
Content-Disposition: inline
Content-Type: application/hal+json; charset=utf-8
Date: Thu, 19 Jan 2023 00:39:00 GMT
Server: nginx/1.18.0 (Ubuntu)
Vary: Accept-Encoding
X-Ratelimit-Limit: 101
X-Ratelimit-Remaining: 100
X-Ratelimit-Reset: 1
{
"_links": {
"account": {
"href": "http://example.com/accounts/{account_id}",
"templated": true
},
```
Horizon and Soroban-RPC included the host (hostname:port) in …
=> Pass through host from http request to horizon and soroban-rpc

start
Emit logs to stdout containing the current state of stellar-core.
Whilst the stellar-core logs are available on the instance, it would be helpful, they're noisy, and somewhat advanced. Stellar-core has an endpoint that presents a rather friendly state of stellar-core. Multiple folks have expressed interest that being visible in the container logs. Stellar-core is the core component of the quickstart image. Everything hinges on its state, and whether it is caught up. While we probably shouldn't put state and logs like this for every application, stellar-core's state feels important enough that it could be outputted here. When folks connect to networks like futurenet or testnet and need to wait 5 minutes to join the network, this gives them clear feedback that nothing is wrong and they just …
=> Emit stdout status of stellar-core

common/supervisor/etc/supervisord.conf
Configure supervisord with `user=root`.
Supervisord assumes if it is running as root that the user has made a mistake and is accidentally running it as root. It prints out a long warning message that looks like this:
> 2023-01-25 06:01:34,140 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
This log comes out in the container logs and is distracting. A user could think something is wrong. At best it takes up screen space for something that is okay and needs no action.
We run supervisord as root, and it's a common practice in Docker containers.
If we configure supervisord with a user, telling it which user we expect it to run as, …
=> Silence the long user=root error supervisord outputs

start
Prefix supervisor container logs with its name.
The other applications that log to the container logs include their name on the front. Supervisor is the odd-one compared to the others.
=> Prefix supervisor container logs with its name

README.md, start
Add a `--logs` option that when set causes the logs of services (stellar-core, horizon, soroban-rpc) to be output to the container logs. Logs are disambiguated from each other by prefixing them with their service name colored, similar to the same output formatting of other popular tools like docker-compose, and foreman.
When the image runs for most development and testing use cases a developer doesn't need to see the logs, but when they do, they need to shell into the container or mount a volume to capture those logs as files. Working on the image is a common time that we need to be viewing the logs. Being able to chuck an option on the end to get all the logs at once is much more convenient than needing to shell in and grep files.
The output of the application is unchanged when the …
=> Add option for outputting service logs to container logs

.github/workflows/build.yml, .github/workflows/manifest.yml
Don't push manifests for forks.
We don't push images for forks, but looks like we try and push a manifest for forks and it errors saying the images don't exist. The error is valid, the images don't exist because we don't push them.
=> Fix PRs from forks

.github/workflows/build-latest.yml
Build an arm64 image for the :latest variant and publish a multi-arch manifest for :latest containing both amd64 and arm64.
In #416 the version of stellar-core for latest was upgraded to v19.7.0 which contained a fix for building for arm64. The latest variant is otherwise ready to be built for arm64 and was just waiting for this release.
=> Support arm64 on :latest variant

.github/workflows/build-soroban-dev.yml, test_soroban_rpc_up.go
Update the `soroban-dev` image to build from the Soroban Preview 7 component source tag versions.
=> updated soroban repo versions to preview 7 tags

Dockerfile
Remove dependency iproute2. Update libc++ dependencies from 10 to 12.
It doesn't appear that iproute2 is required, as stellar-core is able to sync to testnet without issue when they aren't installed.
In the stellar-core repo the docker image uses version 12 now for libc++. We should install the same version here too.
=> Update stellar-core deps

common/soroban-rpc/bin/start, start
Use ports for services when polling status, instead of using the nginx port.
In some places we use the nginx port when polling the status of services, and in others we use the application port. In the places where the application port is used, there's no issue. In places where the nginx port is used, seeing curl or something during that status poll step getting stuck indefinitely. It's unclear why this is happening, but this seems to be a difference that doesn't need to be different.
I tested this deployed to digital ocean and it fixes the issue with the status polling not working.
=> Use ports for services when polling status

.github/workflows/build-soroban-dev.yml, .github/workflows/build.yml, common/soroban-rpc/bin/start, futurenet/soroban-rpc/etc/soroban-rpc.env, start
=> soroban-rpc: Remove dependency on Horizon

.github/workflows/build-soroban-dev.yml, .github/workflows/build.yml
Increase CI resources when building soroban-rpc.
I've noticed that CI has started failing to build soroban-rpc while attempting to update the crates.io index. The logs are not decisive, but they look like resources are being exceeded. The resource most likely to be exceeded here is a free space limit.
Upping resources is the simplest way to address this problem without making changes to the soroban-rpc repo. We need to do this in a way that doesn't require changing the repo because we need to be able to build previously tagged versions of soroban-rpc.
In Rust 1.70 cargo, which will be released in 13 days, will move to using a sparse registry and it will no longer need to check out the entire index. When that happens we can revert this change.
We just seem to be unlucky this has started …
=> Fix builds of soroban-rpc

.github/workflows/build.yml, Makefile
Retain .git directory when building soroban-rpc via docker.
The soroban-rpc build process assumes the .git directory is present. Docker, when using buildkit, by default doesn't include the .git directory in the built image as an optimization.
There's an error popping out in builds of soroban-rpc about the .git directory missing.
It's unclear how long this has been going on for, or what impact it has had.
In any case it looks like soroban-rpc needs the .git directory, and we can tell Docker to keep it in the working directory. We already do this for stellar-core for the same reason.
=> Retain .git directory when building soroban-rpc

start
Fixes https://github.com/stellar/quickstart/issues/456
Previously the `start` script was polling for soroban-rpc on the wrong port+path, so the health check would never succeed. Not sure why it was working before.
=> Fix #456 where soroban-rpc logs waiting forever

.github/workflows/build-latest.yml, .github/workflows/build-testing.yml
updating the non-soroban image versions to latest horizon 2.26.0 release.
=> bump horizon ref to 2.26.0

.github/workflows/build-latest.yml, .github/workflows/build-testing.yml
update horizon to 2.26.1-374
patch for horizon issue
will validate upon landing
N/A
=> update horizon to 2.26.1-374

Dockerfile, dependencies
Remove unnecessary packages and steps from the image.
We're installing things and leaving things in the image that take up about 25% of the image, but aren't needed for it to run. This image is ideally easy for a wide range of people to use. Not everyone has fast internet.
Some of the tools being removed were never needed and are only needed if building from source. Others look like they were there out of convenience when hacking on the image. For that latter case, folks can install whatever they need as they need it.
=> Remove unnecessary packages and steps from the image

Makefile
Add targets to Makefile for building the image in the latest, testing, and soroban-dev configurations. Reorganize the Makefile so it is top down rather than bottom up.
To make it easier to develop on this image and build it from source locally.
=> Add convenience targets to Makefile

futurenet/core/etc/stellar-core.cfg
We want to deprecate and remove this flag since this behavior is not configurable in p20 (see https://github.com/stellar/stellar-core/issues/3933). Currently, setting this to true has no effect anyway, since the versions of core we're running set the default to true. So this should result in no material/function change.
=> Remove usages of LIMIT_TX_QUEUE_SOURCE_ACCOUNT

README.md
Remove instructions from readme about customizing files on persistent volumes.
The instructions currently set someone up to fail because they describe a use case that is misaligned with the goals of the image, and misaligned with the actual maintenance that takes place on this image.
This image is for development and testing, both in the local form, and in the form of being able to deploy the image to simple PaaS environments in a short lived form. (Note that helm charts and other methods for installing and hosting the Stellar services exist for longer form and more complex environments.)
The organization of the files is particularly brittle. When maintaining the image for its primary purpose it is common that we need to change the organization of the files in ways that make the image …
=> Remove instructions from readme about customizing files

.github/workflows/build-soroban-dev.yml, Makefile
consistent ref to the v20.0.0rc1 tag for core, used commit hash setting on earlier pr - https://github.com/stellar/quickstart/pull/483
=> updated core ref on build-soroban-dev target

start
Change references to the standalone network to local that were added in https://github.com/stellar/quickstart/pull/492.
The standalone network was renamed to local, and that PR used the name standalone for some checks, meaning the result of the checks will never run.
=> Fix standalone -> local refs in container

.github/workflows/build-soroban-dev.yml, Makefile
Update the existing soroban development branch from 20.0.0-rc1 to 20.0.0-rc2
=> update rc1 -> rc2

README.md
Remove references to the `:soroban-dev` variant from instructions for how to use soroban on the image, replacing them with `:testing`.
The testing variant contains soroban functionality now. There's little reason for folks to use the soroban-dev variant. We might remove the soroban-dev variant, or we might not, but regardless most devs should use testing for testing, rather than soroban-dev now that soroban is available there.
=> Update docs about how to dev with quickstart and soroban

README.md
Update the readme instructions for Makefile use to include the current variables that can be set.
The variables have become out of date.
=> Fix readme instructions for Makefile use

testnet/soroban-rpc/etc/soroban-rpc.cfg
Change the friendbot URL set for testnet to `https://friendbot.stellar.org/`.
It's set to `https://friendbot-testnet.stellar.org/` which doesn't exist. Looks like we typod the name in the config.
This prevents anyone from using quickstart to fund accounts when using the soroban-cli.
Close #505
=> Fix friendbot URL set for testnet

.github/workflows/build-soroban-dev.yml, .github/workflows/build-testing.yml, Makefile
Update testing/soroban-dev with stellar-core v20.0.0-rc.2.1.
To get a fix for stellar-core high limit override that is causing contracts that work on testnet and futurenet to not work on local.
=> Update testing/soroban-dev with stellar-core v20.0.0-rc.2.1

.do/deploy.template.yaml, README.md, start
Always enable Soroban diagnostic events on local, unless explicitly disabled.
Most of the time when folks are using quickstart in local mode they're developing locally or running quickstart in CI. In these modes diagnostic events are critical for understanding what's happening when things go wrong, and debugging during testing and development.
Much like how we enable other test capabilities in local, we should enable diagnostics because that's the most sensible default for developing in local.
We shouldn't change the default for testnet/pubnet, because diagnostics cause unmetered execution and on testnet/pubnet there's no guarantee other peoples contracts being executed would not cause unreasonable resource consumption.
The addition of the ability to disable on local is so that the …
=> Always enable Soroban diagnostic events on local

README.md, common/nginx/etc/conf.d/horizon.conf, common/nginx/etc/conf.d/soroban-rpc.conf, common/nginx/etc/nginx.conf, futurenet/nginx/etc/conf.d/friendbot.conf, local/nginx/etc/conf.d/friendbot.conf, testnet/nginx/etc/conf.d/friendbot.conf
Replace the single one nginx file with multiple nginx files, one for each service, and configure the friendbot config differently for testnet and futurenet to point to the hosted faucets.
So that developers can write tests against their local quickstart that use friendbot regardless of whether the quickstart is running in local mode, testnet mode, or futurenet mode.
Close #57
=> Make friendbot work in testnet mode

start
Output the version of stellar-core, horizon, and soroban-rpc to container logs on start.
```
Starting Stellar Quickstart
versions:
stellar-core:
v20.0.0-rc.2.1
rust version: rustc 1.72.1 (d5c2e9c34 2023-09-13)
soroban-env-host: 
curr:
package version: 20.0.0-rc1
git version: f19ef13363a1e0cbff7b100c0599a1d63dea88a6
ledger protocol version: 20
pre-release version: 57
rs-stellar-xdr:
package version: 20.0.0-rc1
git version: d5ce0c9e7aa83461773a6e81662067f35d39e4c1
base XDR git version: 9ac02641139e6717924fdad716f6e958d0168491
horizon:
horizon-v2.27.0-rc1-(built-from-source)
go1.20.10
soroban-rpc:
soroban-rpc 20.0.0-rc4 (bce5e56ba16ba977200b022c91f3eaf6282f47eb) HEAD
stellar-xdr 9ac02641139e6717924fdad716f6e958d0168491
mode: ephemeral
network: local
network passphrase: Standalone Network ; …
```
=> Output versions of software to container logs on start

.github/workflows/build-soroban-dev.yml, .github/workflows/build-testing.yml, Makefile
=> Update soroban-dev image to use 20.0.0 versions

.github/workflows/build-soroban-dev.yml
updated the image meant for futurenet(soroban-dev) to include the fix for preflight instruction padding - https://github.com/stellar/soroban-tools/pull/1127
=> update soroban dev image to rpc 20.0.2 for preflight fees padding

Makefile
Update Makefile versions for testing and soroban-dev to match the CI
At some point they got out of sync.
=> Update Makefile versions for testing/soroban-dev to match the CI

common/supervisor/etc/supervisord.conf.d/horizon.conf, start
Run supervisord in a new environment that doesn't inherit the shell.
Supervisord and its subprocesses inherit the shell's environment variables.
This is problematic since environment variables are a shared space and there's no guarantee that setting an environment variable would make sense for all sub processes.
We have a case where this has caused problems. The quickstart image uses the `NETWORK` environment variable, and so does Horizon. For the longest time we have had issues running the quickstart image in certain situations, and it turns out what those situations had in common was they were setting the network of the image via an environment variable `NETWORK` to a value that worked with the quickstart image start script but didn't work with Horizon. Some values worked for both, some …
=> Fix unintended environment variable config passthrough to services

.github/workflows/build-soroban-dev.yml, .github/workflows/build-testing.yml
update the testing for testnet and soroban-dev for futurenet images to use core v20.1.0
=> bump core for testing/soroban images to v20.1.0

.github/workflows/build-future.yml
Rename :soroban-dev to :future
To the given the image a name that communicates intent, and connects it to the future network.
The name soroban-dev is now confusing. All quickstart image variants contain soroban now.
The releases of soroban-dev are typically related to the futurenet releases. They're experimental / preview releases that have no compatibility guarantees.
Close #530
Dependent on feedback on this comment: https://github.com/stellar/quickstart/issues/530#issuecomment-1903217821
=> Rename :soroban-dev to :future

README.md
Update refs to :soroban-dev to ref :future in readme.
I forgot to update the readme in:
- #548
=> Update refs to :soroban-dev to ref :future in readme

.github/workflows/build-future.yml, .github/workflows/build-latest.yml, .github/workflows/build-testing.yml, Makefile
new horizon release 2.28.0 is out, bump all image variants.
=> bumped horizon refs to 2.28.0

common/postgresql/etc/postgresql.conf
Ran into issues with too many connections on my linux destop with 128 threads. This seemed to be the magic number.
It would be nice to have a way to override this at runtime, but for now this should be good enough.
=> fix: increase postgres max_connections to 150

.github/workflows/build-latest.yml, .github/workflows/build-testing.yml, Makefile
Update the latest target for quickstart build with stable core v20.2.0.
Also updated xdr and rpc ref for latest build.
=> Update latest target to stable core v20.2.0

.github/workflows/build-future.yml, .github/workflows/build-testing.yml, .github/workflows/build.yml, Dockerfile, Makefile, README.md
Remove `CORE_SUPPORTS_ENABLE_SOROBAN_DIAGNOSTIC_EVENTS` config and related params.
It's no longer needed. All versions of core released in all the variants of the quickstart image support `ENABLE_SOROBAN_DIAGNOSTIC_EVENTS`.
=> Remove CORE_SUPPORTS_ENABLE_SOROBAN_DIAGNOSTIC_EVENTS config

Dockerfile.horizon
Bump go version to 1.22 for Horizon
https://github.com/stellar/go/issues/5230
=> Bump go version to 1.22

.github/workflows/build-future.yml, .github/workflows/build-latest.yml, .github/workflows/build-testing.yml, Makefile
update image build variants to use latest horizon release 2.29.0
=> bump horizon refs to 2.29.0

test_horizon_core_up.go
Set timeout of horizon core up test to 10 mins.
The timeout of the horizon core up test is currently set to 6 mins. It seems to have recently been failing a few times around the 6 min 15 sec mark. The timeout is there so tests don't run extraordinarily long due to a bug, so 10 mins seems appropriate.
=> Fix flakey build

.github/workflows/stale.yml
Update the stale CI job to v9.
So that when it closes issues, they will be marked as closed and not completed, rather than closed and completed as it does today with v4.
=> Update stale job to v9

.github/workflows/build-future.yml, .github/workflows/build-latest.yml, .github/workflows/build-testing.yml, Makefile
Bump horizon to [v2.30.0](https://github.com/stellar/go/releases/tag/horizon-v2.30.0)
=> Bump horizon to 2.30.0

.github/workflows/build-future.yml, .github/workflows/build-testing.yml, Makefile
Update testnet and futurenet image variants to latest xdr, core and rpc release.
This is the last part of our release process. We will be asking ecosystem to test in Futurenet and Testnet so need to have the latest available in quickstart.
=> Update testnet and futurenet image variants to latest xdr, core and rpc release

.github/workflows/build-start.yml
Re-enable future image builds.
Horizon and the RPC specified in the future builds now supports setting `ENABLE_DIAGNOSTICS_FOR_TX_SUBMISSION` on the stellar-core they run.
=> Reenable future builds

Makefile, start
Default to cores max protocol version in local mode when no default specified.
In #594 I removed the automatic default and replaced it with an explicit default because nearing protocol releases we have versions of software being updated in quickstart without coordination, which is good, and having local always startup a network based on core's max supported protocol version meant that in some cases it would start networks that the image as a whole was not ready to run.
When I removed the automatic default I made it so that an explicit default had to be set. That requirement was somewhat unnecessary. For most uses of quickstart simply using what core thinks the version should be is fine, and it's those edge cases where we need it specified.
I'd like to keep it as so so that in other uses …
=> Default to cores max protocol version in local mode when no default specified

.github/workflows/build-future.yml, Makefile
Set the default protocol version to 21 for future
Future builds have versions of core, rpc, and horizon that should support protocol 21, so the local should default to running that protocol version. The only reason to have a lower version is if all the software doesn't yet support the latest because then startup of a local will fail with the default protocol version.
=> Set the default protocol version to 21 for future

.github/workflows/build-future.yml, .github/workflows/build-latest.yml, .github/workflows/build-testing.yml, Makefile
Also update XDR/RPC references for the 'latest' build in order to have consistent v21 stack.
=> Update quickstart to use stable Core v21.

.github/workflows/build-testing.yml, Makefile
Update core and rust xdr refs to v21.1.0 for testing targets
=> Update core and rust xdr refs to v21.1.0 for testing targets

.github/workflows/build.yml, README.md, start
when using `--local --enable core,,` do not start the horizon/friendbot service in container, only core service will be running. 
this removes prior default behavior, which started horizon and friendbot services automatically when `--local` was used.
we are using quickstart for new end-to-end integration tests now, and noticed with `--enable core,,` if `--local` was used, quickstart would still start horizon/friendbot in container, here is reference of how the test uses these flags:
https://github.com/stellar/go/pull/5370/files#diff-1c787ef8e522ba695cb843ceef6c93e842a3cfc319085d6b78349a1c4ec201abR279
the testing environment only needs the local core validator/history archive server available which quickstart automates the provisioning of these services very conveniently(and reliably for …
=> '--enable core --local' only runs core, no ancillary services

local/nginx/etc/conf.d/history-archive.conf
Expose history archive on `/archive`.
For use with the `stellar snapshot` command being added in:
- https://github.com/stellar/stellar-cli/pull/1368
=> Expose history archive on `/archive`

.github/workflows/build-future.yml, .github/workflows/build-testing.yml, Makefile
=> Update core in testing/future

.github/workflows/build-future.yml, .github/workflows/build-latest.yml, .github/workflows/build-testing.yml, Makefile
The latest stable release of horizon is v22.0.1
=> Update horizon version to 22.0.1

.github/workflows/build-latest.yml, Makefile
Pubnet has upgraded to v22, so this value can be bumped now.
=> Bump latest to v22

Dockerfile, Makefile, start
Error during image build if the `PROTOCOL_VERSION_DEFAULT` variable is not set.
Images won't reliably work unless the arg is set. The image does fall back to whatever core's max supported protocol version, but we moved away from that a while ago and missed removing that check. The reason we don't rely on that anymore is that core's max supported version is not representative of the entire images max supported version because the image runs multiple software and it's common for core to release a new version before other software.
=> Require PROTOCOL_VERSION_DEFAULT

Dockerfile.horizon
We are now building horizon with Go version 1.23, see https://github.com/stellar/go/pull/5561
=> Use Go version to 1.23 when building horizon

README.md
Removes 'local' argument from container start command in README.
The argument is optional as of:
- https://github.com/stellar/stellar-cli/pull/1852
=> Update stellar-cli command in README

Dockerfile.xdr
After [new rustup change](https://blog.rust-lang.org/2025/03/02/Rustup-1.28.0.html#whats-new-in-rustup-1280) we need to manually install toolchains.
As the result, a lot of our build tooling started to fail (e.g. [systems test](https://github.com/stellar/system-test/pull/120))
This PR tries to fix that
Before:
```
> docker build . -f Dockerfile.xdr --build-arg REPO=https://github.com/stellar/rs-stellar-xdr --build-arg REF=c356a8cdcf59e91bd2224edda45eff337335ccfb
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
Install the buildx component to build images with BuildKit:
https://docs.docker.com/go/buildx/
Sending build context to Docker daemon  1.225MB
Step 1/8 : FROM rust:1.85.0 AS builder
1.85.0: Pulling from library/rust
Digest: …
```
=> Update XDR dockerfile

Dockerfile.xdr, action.yml
Adds action to run quickstart in the form we usually use in our workflows.
Currently supports Linux and Mac (x84-64 only)
=> Add `action.yml`

Makefile
Update Horizon to the latest version: [Horizon v22.0.3](https://github.com/stellar/go/releases/tag/horizon-v22.0.3).
=> Update Horizon version 22.0.3

start
Add ability to override the network passphrase in local mode.
Allows developers using the image to run local mode with a different network passphrase. Helpful when running a shared test network and wanting to give it a meaningful and unique network name, or wanting to ensure that txs signed for a test network do not overlap with any other test networks.
The ability to get a unique network name is already supported by the ability to set a randomized network passphrase, but that can be inconvenient to use in some situations since every boot will result in a new passphrase.
Close #299
Intended on merging to `main` after:
- #687
=> Allow setting custom network passphrase in local mode

common/friendbot/etc/friendbot.cfg, start
Update friendbot configuration file with placeholders that are replaced during initialization with the network's passphrase and root secret key.
Friendbot has a fixed configuration in the image that only works with the network passphrase set to a specific phrase. However the image is designed to be used as a development / testing network with random passphrases, so that when deploying to a shared public URL the network has a unique network passphrase so that txs signed for it don't overlap with any other network.
Close #335 
Blocks:
- #299 
- https://github.com/stellar/stellar-docs/pull/1543
=> Fix friendbot not starting with different network passphrases

Dockerfile.lab, start
=> Add changes related to lab being included

Dockerfile, Dockerfile.lab, common/lab/bin/start
Reduce the lab files embedded into the image to only the files needed to run lab.
Uncompressed: 0.70G
Compressed: 0.23G
https://hub.docker.com/layers/stellar/quickstart/v481-future/images/sha256-7480e1b3f568ee4848bb907854266de13e04e83a8610b6bdafa5ed5bf6495d33
Uncompressed: 2.33G
Compressed: 0.60G
https://hub.docker.com/layers/stellar/quickstart/v484-future/images/sha256-0528af8c7585d32533bc0ba2b33772f18c4809f27d0183e0cd40f48399e8897c
Uncompressed: 0.91G
Compressed: 0.29G
https://hub.docker.com/layers/stellar/quickstart/pr706-v485-future/images/sha256-75cd5dc2f3a8c6e22765fdfdeb4f9ef4929ca90c7b9ad3eb1eed6c97550ec153
Quickstart got bigger when we added lab. We followed the instructions in the lab repo for how to use the production build, but it turns out lab actually builds a standalone …
=> Make lab smaller

README.md
Add HTTP paths for Horizon, RPC, Lab, and Friendbot near the top of the readme, and make an assortment of other changes.
Provides clear access points for all services. The document doesn't actually mention near the top where folks can find the software's APIs available. The other changes are small improvements, some of which fix out-dated information.
=> Add HTTP paths to readme and other minor changes

Dockerfile, start
Create a symlink from the default supervisorctl config location to the Stellar supervisorctl config location.
Allows supervisorctl to find the config automatically without requiring additional command options.
In #690 I changed the way that supervisorctl communicates with supervisord to use inet_http_server instead of unix_http_server. This had the side effect of needing to specify the config file location when running supervisorctl, because the default config stored at /etc/supervisor/supervisor.conf specifies supervisorctl should connect via unix_http_server. So after that change running supervisorctl will read the default config and try to connect to the unix socket rather than the inet.
All of this arises from the fact that the image has always had two supervisor.confs, the one in the …
=> Fix supervisorctl command

.github/workflows/build.yml
For each software component being built, tag the git ref configured for the build and derive its git commit sha, using that sha for caching and the rest of the build instead of the original git ref.
The build workflows heavily use caching and assume that the git refs configured to build are immutable. This means we can only use tags or commit shas as the input for what to build. This has led to mistakes in the past where someone has specified a branch then after rebuilds hasn't seen the changes be applied because the previous build cached the docker image from a branch build. This will give us more flexibility, such as making an image that builds images from software component's main branches, whilst still being able to cache each image build for each commit.
=> Support building images from software component's branches

.github/workflows/build.yml
Add 'if: always()' condition to build and test jobs to run regardless of prior job failures and skips.
Earlier jobs in the flow can be skipped because of cache usage, and GH workflows will not run the build job if an earlier job skipped. We could have made those earlier jobs still run and skipped steps instead, but because those earlier runs use high cost runners, it is more cost effective and in many cases time effective to skip the entire job.
I had removed the always in https://github.com/stellar/quickstart/pull/737.
=> Fix issue in running build/test jobs

.github/workflows/build.yml, Dockerfile, Dockerfile.horizon, Dockerfile.lab, Dockerfile.xdr, Makefile
Restructure Docker build process leveraging multi-stage builds so that intermediary images contain only the files needed in subsequent stages.
Reduce size of the intermediary images that are saved and loaded across build steps and are cached and loading in subsequent builds as well. Some of the newer images we added, like the lab, are large enough that the file loading takes more than 1 min in each job that needs to load the image file. The images contain all the files from the build, but we only need them to contain the final artifacts.
As a comparison of impact:
- The lab intermediary image was 2.2GB, but is now 0.08GB.
- It used to take ~3 minutes to move the image from cache to artifacts and load it into the docker runtime.
- It now takes ~7 seconds.
Saving a few minutes doesn't sound …
=> Reduce build time by reducing the size of intermediary build stages to necessary files only

.github/workflows/action-test.yml, .github/workflows/build-future.yml, .github/workflows/build-latest.yml, .github/workflows/build-start.yml, .github/workflows/build-testing.yml, .github/workflows/build.yml, .github/workflows/manifest.yml, action.yml
Fix which image the action test pr build runs on.
Move the action-test workflow to run after each individual image build.
Replace manual Docker setup using Homebrew with official Docker GitHub Action.
The action-test workflow was waiting for all image builds to finish, but it can start running on each image separately. Also the tag prefix that was being used by the action build didn't include the tag pr prefix because the tag pr prefix was being set lower down and the tag prefix known higher up didn't contain it.
The homebrew install and setup of lima is really slow, leading to the action taking 12-12 minutes on a macos-13 instance. That's too long for realistic usage inside CI. Docker have an action that does a setup of lima and docker, and maybe it is faster. Giving it a go in this …
=> Improvements to the GitHub Action tests

.github/workflows/build.yml
Update the cache key for the horizon image build to include CACHE_ID and use the horizon SHA.
The cache key for the horizon image is missing the cache id that helps with invalidating all the images when needed. The cache key is also embedding the rpc sha instead of the horizon sha. That second part is a pretty bad bug, but it was only recently committed and the impact should be small.
=> Fix horizon cache key in image build

.github/workflows/action-test.yml, .github/workflows/build-start.yml, .github/workflows/build.yml
Reduce the matrix for which OSes the action tests run on for PRs that do not change the action.
Also, make the action tests always run on the main branch push events.
The action tests take a _long_ time to run on those additional OSes, but are fast on ubuntu.
The additional change to always run on main is so that we still find out if the action tests fail on any commit. Today the action tests don't run on main for some reason.
=> Run Action Tests only in PRs if action.yml changes

.github/workflows/action-test.yml
Switch the action test workflow to use cheaper runners.
Reduce costs associated with GitHub Actions. Make the wait time less because the cheaper runners are more available. I don't think these tests require the beefy runners.
=> Use Cheaper Runners in Action Test

.github/workflows/build.yml, Dockerfile, Dockerfile.core, Dockerfile.xdr, Makefile
Move the Core Dockerfile used to build core into the repo, and reduce the image artifact by making its final step minimal.
Reduce the size of intermediary images that are stored and passed around between jobs. It reduces the time copying images between jobs, and reduces the total size of artifacts stored in GitHub actions.
=> Move Core Dockerfile into repo and reduce size

.github/workflows/build.yml
Use the free arm runners that are github hosted instead of the custom runner.
Now that GitHub provides free and standard arm runners there's no longer a need to use the custom runner.
=> Use free arm runners instead of custom runner
