dependencies, install
=> Exit on error during building an image

README.md
see https://github.com/stellar/docker-stellar-core-horizon/commit/cdb978463c90a531743c08a09993b817117b8de8 for postgres version change
=> Keep Readme consistent with Postgres version change

pubnet/core/etc/stellar-core.cfg, testnet/core/etc/stellar-core.cfg
This configures default watcher quorum set to be Tier 1 validators
Closes #144
=> update qset config to new format

.circleci/config.yml
This should fix issues connected to [key issues](https://app.circleci.com/pipelines/github/stellar/docker-stellar-core-horizon/48/workflows/b53ef272-1c37-4fd9-9cea-7c58351ac524/jobs/28) in Circle-CI.
=> Overwrite Circle checkout command

Dockerfile, Dockerfile.testing, README.md, common/supervisor/etc/supervisord.conf, dependencies, install, start
* install gnupg1, rsync, wget
* use Postgresql 12
=> Upgrade to Ubuntu 20.04 (Focal)

.github/workflows/test.yml
Add tests for standalone mode.
We're working on it in #276.
=> Add tests for standalone mode

.github/workflows/build.yml, README.md, common/nginx/etc/nginx.conf, start
Remove trailing spaces on lines and clean up some formatting.
It seems we've started to accrue trailing spaces on lines throughout some files in this repository. In IDEs that highlight trailing spaces it is distracting seeing so much scattered spaces. We should keep these files tidy.
=> Remove trailing spaces on lines

.github/workflows/build-latest.yml, .github/workflows/build-testing.yml
latest stable core release v19.9.0
=> Bump core image to v19.9.0

.github/workflows/build-testing.yml
=> Bump core testing image to v19.10.0rc1

.github/workflows/build-latest.yml, .github/workflows/build-testing.yml
latest stable core release v19.10.0
- build-latest
- build-testing
=> Bump core image to latest stable release v19.10.0

.github/workflows/build-testing.yml
=> Bump core testing image to v19.11.0rc2

.github/workflows/build-soroban-dev.yml
pull in the new minor patch version of soroban horizon- https://github.com/stellar/go/releases/tag/soroban-v0.0.8.2
includes fix on state verification for asset stats - https://github.com/stellar/go/pull/4884
=> update soroban enabled horizon version 

.github/workflows/build-latest.yml, .github/workflows/build-testing.yml
Stellar core release v19.10.0
build-latest
build-testing
=> Update core image to latest release v19.11.0

.github/workflows/build-testing.yml
=> Bump core test image to v19.12.0rc2

.github/workflows/build-latest.yml, .github/workflows/build-testing.yml
Stellar core release v19.12.0
build-latest
build-testing
=> Update core image to latest release v19.12.0

.github/workflows/build-latest.yml, .github/workflows/build-testing.yml
We had a partner recently ask for an updated quickstart image with this version of core
=> Update core to latest release v19.13

.github/workflows/build-latest.yml, .github/workflows/build-soroban-dev.yml, .github/workflows/build-testing.yml, Makefile
This PR update the core and soroban-rpc builds to use
- core 20.0.0.0-rc2
- fix database schema isssue
- fix upgrade issue
- soroban-rpc 20.0.0.0-rc3
- fix prng issue
- fix temporary entries issue
=> update soroban-rpc rc3

.github/workflows/build-testing.yml, Makefile
Will hold off on merge until after reset
=> Update testing image with stable testnet versions

local/core/etc/config-settings/testnet.json, local/core/etc/config-settings/unlimited.json
Update testnet.json to reflect changes to https://github.com/stellar/stellar-core/blob/master/soroban-settings/phase1.json, and also update unlimited.json to use updated cost params.
Sometime in the future, we should make quickstart pickup tesnet.json directly from core.
=> Update Soroban network settings files to reflect recent changes

.github/workflows/build-latest.yml, .github/workflows/build-soroban-dev.yml, .github/workflows/build-testing.yml, Makefile, start
Update versions of software in latest image to v20.
v20 is stable and is deployed on SDF nodes, and we should make it available in quickstart.
=> Update versions of software

.github/workflows/build-latest.yml, .github/workflows/build-soroban-dev.yml, .github/workflows/build-testing.yml, Makefile
https://github.com/stellar/soroban-tools/releases/tag/v20.1.0
=> Bump RPC version on all images

Makefile, local/core/etc/config-settings/testnet.json, local/core/etc/config-settings/unlimited.json
Updates the makefile to the same version bumped in https://github.com/stellar/quickstart/pull/544
=> Bump core in local Makefile to 20.1.0

Makefile
Update makefile with :soroban-dev -> :future
I forgot to update the makefile in:
- #548
=> Update makefile with :soroban-dev -> :future

.github/workflows/build-latest.yml
Update stellar-core to v20.1.0 in latest image
Close #552
=> Update stellar-core to v20.1.0 in latest image

.github/workflows/build-future.yml, .github/workflows/build-latest.yml, .github/workflows/build-testing.yml, Makefile
use new horizon release https://github.com/stellar/go/releases/tag/horizon-v2.28.1
=> updated horizon to 2.28.1

.github/workflows/build-future.yml, .github/workflows/build-latest.yml, .github/workflows/build-testing.yml, Makefile
Update horizon to [v2.28.2]( https://github.com/stellar/go/releases/tag/horizon-v2.28.2)
=> Update Horizon to version 2.28.2

.github/workflows/build-future.yml, .github/workflows/build-latest.yml, .github/workflows/build-testing.yml, Makefile
bump all variants to horizon 2.28.3
=> use horizon 2.28.3

start
Display logs for all stellar-cores running.
Logs output the status of the main stellar-core node, but not the other stellar-cores that are run by horizon and rpc. This leads to some false feedback where maybe the main node catches up by horizon is lagging behind and there's no visibility of that. Also this leads to no feedback when running only rpc or horizon since no status of their stellar-cores are outputted.
These logs show when a stellar-core node and a soroban-rpc (with stellar-core as well) are running together. You can imagine if only the rpc was running, then the `stellar-core(rpc)` logs would be the only ones showing. This is comparable with today where you get no stellar-core logs when only the rpc is running.
```
soroban-rpc: started
stellar-core(rpc): Joining SCP; Catching up …
```
=> Display logs for all stellar-cores running

.github/workflows/build-testing.yml, Makefile
Update CI/make to use protocol 21,  now that all the deps should support it.
=> Update CI/make to use protocol 21, 

start
Required for the upcoming core release due to https://github.com/stellar/stellar-core/pull/4351.
=> Handle upcoming change to the core get settings upgrade command

.github/workflows/build-future.yml, .github/workflows/build-latest.yml, .github/workflows/build-testing.yml, Makefile
Update core ref to latest stable v21.1.0 for all targets
=> Update core ref to latest stable v21.1.0 for all targets

.github/workflows/build-future.yml, .github/workflows/build-testing.yml, Makefile
=> Update rpc to 22 rc3

.github/workflows/build-future.yml, .github/workflows/build-latest.yml, .github/workflows/build-testing.yml, Makefile
Bump core to latest stable v22.0.0
=> Bump core to latest stable v22.0.0

.github/workflows/build-future.yml, .github/workflows/build-latest.yml, .github/workflows/build-testing.yml, Makefile
See [release notes](https://github.com/stellar/stellar-rpc/releases/tag/v22.1.2).
=> Bump patch RPC to v22.1.2

.github/workflows/stale.yml
Change stale time to 90 days, and disable autoclosing.
Product ask.
N/A
=> Change stale workflow settings.

README.md
- Info for how to enable Lab
- port for Lab
- Add license badge
- Add deepwiki badge
- Add better intro
=> Update README to add details

start
Resolves https://github.com/stellar/quickstart/issues/714 and https://github.com/stellar/quickstart/issues/728
=> Futurnet archive fix

local/core/etc/config-settings/p23/testnet.json, local/core/etc/config-settings/p23/unlimited.json, local/core/etc/config-settings/settings_enable_upgrades.json, start
This PR updates the config upgrade process to first allow larger upgrades, which lets us upgrade to the exact settings testnet uses. This will make future updates to the file easier, as all you'll have to do is paste the current testnet settings.
=> Two step upgrade

local/core/etc/config-settings/p23/unlimited.json
Fix the unlimited config option
=> Remove extra cost type

.github/workflows/build.yml
Free up disk space at start of test runs that use pubnet.
The tests with pubnet are consistently running out of disk space.
=> Fix pubnet runs running out of disk space
